import { Inter, Noto_Sans_Display } from "next/font/google";
import "./globals.css";
import { NewsProvider } from "@/contexts/NewsContext";

const sans = Noto_Sans_Display({ subsets: ["latin"] });

export const metadata = {
  title: "NIT Jamshedpur Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NewsProvider>
    <html lang="en">
      <body className={sans.className}>
        {children}
        </body>
    </html>
    </NewsProvider>
  );
}
