import { Inter, Noto_Sans_Display } from "next/font/google";
import "./globals.css";
import { NewsProvider } from "@/contexts/NewsContext";
import Navbar from "@/components/Navbar/navbar";
import { MobileNavbar } from "@/components/MobileNavbar/mobileNavbar";
import Footer from "@/components/Footer/Footer";

const sans = Noto_Sans_Display({ subsets: ["latin"] });

export const metadata = {
  title: "NIT Jamshedpur Lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NewsProvider>
    <html lang="en">
      <body className={sans.className}>
        <MobileNavbar/>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
    </NewsProvider>
  );
}
